name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: [7]
        node: [16]
        include:
          # On other platforms
          - node: 16
            os: windows-latest
          - node: 16
            os: macos-latest
          # On old Node.js versions
          - node: 14
            os: ubuntu-latest
          - node: 12
            os: ubuntu-latest
          - node: 10
            os: ubuntu-latest
          # On the minimum supported ESLint/Node.js version
          - node: 10.12.0
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Packages
        run: npm install
      - name: Test
        run: npm test
      - name: Send Coverage
        run: npm run -s codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
